// 化学元素和化合物数据 - 标准化结构
const chemicalData = [
    // 元素周期表主族元素
    {
        symbol: "H",
        englishName: "Hydrogen",
        chineseName: "氢",
        type: "单质",
        atomicNumber: "1",
        atomicWeight: "1.008",
        formula: "H",
        molecularWeight: "1.008",
        category: "非金属",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1766年由亨利·卡文迪什发现",
        origin: "宇宙大爆炸产生，地球上主要来自水和碳氢化合物",
        funFacts: [
            "占宇宙质量的75%",
            "太阳的能量来源于氢核聚变",
            "液氢是火箭燃料的主要成分",
            "氢气球曾用于早期航空"
        ],
        history: "氢气最早由帕拉塞尔苏斯无意中发现，但直到1766年才被卡文迪什确认为独立元素。法国化学家拉瓦锡将其命名为'Hydrogen'，意为'水生成者'。",
        description: "宇宙中最丰富的元素，最轻的气体，易燃易爆"
    },
    {
        symbol: "He",
        englishName: "Helium",
        chineseName: "氦",
        type: "单质",
        atomicNumber: "2",
        atomicWeight: "4.003",
        formula: "He",
        molecularWeight: "4.003",
        category: "稀有气体",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1868年由皮埃尔·詹森和诺曼·洛克耶发现",
        origin: "主要来自天然气井中的放射性衰变产物",
        funFacts: [
            "在太阳日珥的光谱中首次发现",
            "液氦在-271°C以下会变成超流体",
            "人类声音在氦气中会变尖",
            "氦气是目前唯一无法固化的元素"
        ],
        history: "1868年日食期间，法国天文学家詹森和英国天文学家洛克耶同时在太阳光谱中发现未知黄色谱线，洛克耶将其命名为'Helium'，意为'太阳'。直到1895年才被拉姆齐在地球上发现。",
        description: "最轻的惰性气体，不能燃烧，用于填充气球和飞艇"
    },
    {
        symbol: "Li",
        englishName: "Lithium",
        chineseName: "锂",
        type: "单质",
        atomicNumber: "3",
        atomicWeight: "6.941",
        formula: "Li",
        molecularWeight: "6.941",
        category: "碱金属",
        phase: "固体",
        state: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "强碱性",
        discovery: "1817年由瑞典化学家约翰·奥古斯特·阿尔弗韦德松发现",
        origin: "主要从锂辉石和盐湖卤水中提取，地壳中含量约为0.0065%",
        funFacts: [
            "是最轻的金属，密度只有水的一半",
            "锂电池为现代电子设备提供动力",
            "在核聚变反应中用作氚的生产原料",
            "某些锂化合物用于治疗躁郁症"
        ],
        history: "1817年瑞典化学家阿尔弗韦德松在分析透锂长石时发现了锂。1821年英国化学家威廉·托马斯·布兰德通过电解氯化锂首次分离出金属锂。20世纪后期，随着锂电池技术的发展，锂成为重要的战略资源。",
        description: "最轻的金属，用于锂电池"
    },
    {
        symbol: "Be",
        englishName: "Beryllium",
        chineseName: "铍",
        type: "单质",
        atomicNumber: "4",
        atomicWeight: "9.012",
        formula: "Be",
        molecularWeight: "9.012",
        category: "碱土金属",
        phase: "固体",
        state: "固体",
        color: "钢灰色",
        odor: "无味",
        acidBase: "两性",
        discovery: "1798年由法国化学家路易-尼古拉·沃克兰发现",
        origin: "主要从绿柱石矿物中提取，地壳中含量约为0.0002%",
        funFacts: [
            "比钢还硬但重量只有铝的1/3",
            "用于航天器结构材料和卫星反射镜",
            "具有优良的X射线透射性",
            "吸入铍粉尘会导致严重的铍肺病"
        ],
        history: "1798年法国化学家沃克兰在分析绿柱石和祖母绿时发现了铍。1828年德国化学家弗里德里希·维勒和法国化学家安托万·比西分别独立地通过还原氯化铍分离出金属铍。20世纪40年代开始用于核工业和航空航天领域。",
        description: "轻质高强度金属，用于航空航天"
    },
    {
        symbol: "B",
        englishName: "Boron",
        chineseName: "硼",
        type: "单质",
        atomicNumber: "5",
        atomicWeight: "10.811",
        formula: "B",
        molecularWeight: "10.811",
        category: "准金属",
        phase: "固体",
        state: "固体",
        color: "黑色",
        odor: "无味",
        acidBase: "酸性",
        discovery: "1808年由英国化学家戴维和法国化学家盖-吕萨克、泰纳尔分别独立发现",
        origin: "主要从硼砂和硼酸矿中提取，地壳中含量约为0.001%",
        funFacts: [
            "硼纤维比钢还强韧但重量很轻",
            "硼玻璃具有优良的耐热性和化学稳定性",
            "硼酸是天然的杀虫剂和防腐剂",
            "硼中子俘获疗法用于治疗脑肿瘤"
        ],
        history: "1808年英国化学家戴维和法国化学家盖-吕萨克、泰纳尔几乎同时通过还原硼酸发现了硼。19世纪主要用作清洁剂和防腐剂，20世纪随着硼纤维和硼合金的发展，成为重要的工业材料。",
        description: "硬度仅次于金刚石，用于制造硼玻璃"
    },
    {
        symbol: "C",
        englishName: "Carbon",
        chineseName: "碳",
        type: "单质",
        atomicNumber: "6",
        atomicWeight: "12.011",
        formula: "C",
        molecularWeight: "12.011",
        category: "非金属",
        phase: "固体",
        state: "固体",
        color: "黑色",
        odor: "无味",
        acidBase: "中性",
        discovery: "古代已知，1789年拉瓦锡确认为元素",
        origin: "宇宙中第四多的元素，地球上以石墨、金刚石、煤等形式存在",
        funFacts: [
            "碳的同素异形体包括金刚石、石墨、富勒烯、石墨烯等",
            "所有已知生命都基于碳化学",
            "大气中的CO₂是碳循环的重要组成部分",
            "石墨烯是已知最薄的材料，只有一个原子厚"
        ],
        history: "碳自古就被人类认识和使用，以木炭、煤和石墨的形式存在。1789年拉瓦锡通过实验证明金刚石和石墨都是由碳组成，推翻了金刚石是特殊物质的观念。现代化学的发展使碳成为理解有机化学和生命科学的中心元素。",
        description: "构成生命的基础元素，多种同素异形体"
    },
    {
        symbol: "N",
        englishName: "Nitrogen",
        chineseName: "氮",
        type: "单质",
        atomicNumber: "7",
        atomicWeight: "14.007",
        formula: "N",
        molecularWeight: "14.007",
        category: "非金属",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1772年由苏格兰化学家丹尼尔·卢瑟福发现",
        origin: "占空气体积的78%，是蛋白质和核酸的组成元素",
        funFacts: [
            "氮气在常温下化学性质很不活泼",
            "液氮的沸点为-196°C，常用于低温保存",
            "氮循环是地球生态系统的重要过程",
            "氮气可用于食品包装的惰性保护气体"
        ],
        history: "1772年卢瑟福通过实验发现了氮气，他称之为'有害空气'。法国化学家拉瓦锡在1789年将其命名为'azote'，意为'无生命'。后来发现氮是蛋白质的重要组成部分，对生命至关重要。",
        description: "空气中含量最多的气体，惰性"
    },
    {
        symbol: "O",
        englishName: "Oxygen",
        chineseName: "氧",
        type: "单质",
        atomicNumber: "8",
        atomicWeight: "15.999",
        formula: "O",
        molecularWeight: "15.999",
        category: "非金属",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1774年由英国化学家约瑟夫·普利斯特里和瑞典化学家卡尔·威尔海姆·舍勒独立发现",
        origin: "占空气体积的21%，是水和大多数氧化物的组成元素",
        funFacts: [
            "氧气是地球大气中第二多的气体",
            "臭氧(O₃)是氧的同素异形体，保护地球免受紫外线伤害",
            "液氧呈淡蓝色，用作火箭燃料的氧化剂",
            "高压氧疗法用于治疗一氧化碳中毒"
        ],
        history: "1774年普利斯特里通过加热氧化汞制得氧气，舍勒在1772年也独立发现了氧气。拉瓦锡在1775年通过实验证明氧气是空气的一个组成部分，并推翻了燃素说。",
        description: "支持燃烧和呼吸的气体"
    },
    {
        symbol: "F",
        englishName: "Fluorine",
        chineseName: "氟",
        type: "单质",
        atomicNumber: "9",
        atomicWeight: "18.998",
        formula: "F",
        molecularWeight: "18.998",
        category: "卤素",
        phase: "气体",
        state: "气体",
        color: "淡黄色",
        odor: "刺激性",
        acidBase: "酸性",
        discovery: "1886年由法国化学家亨利·莫瓦桑首次分离",
        origin: "以萤石(CaF₂)和冰晶石(Na₃AlF₆)形式存在，地壳中含量约为0.065%",
        funFacts: [
            "是已知最活泼的非金属元素",
            "氟化水可以预防龋齿",
            "聚四氟乙烯(特氟龙)含有氟原子",
            "大气中的氟利昂曾经是臭氧层破坏的主要原因"
        ],
        history: "虽然氟的化合物早已为人所知，但单质氟的分离极其困难。1886年法国化学家莫瓦桑通过电解氟化氢钾首次制得氟气，为此获得了1906年诺贝尔化学奖。",
        description: "最活泼的非金属元素，剧毒"
    },
    {
        symbol: "Ne",
        englishName: "Neon",
        chineseName: "氖",
        type: "单质",
        atomicNumber: "10",
        atomicWeight: "20.180",
        formula: "Ne",
        molecularWeight: "20.180",
        category: "稀有气体",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1898年由英国化学家威廉·拉姆齐和莫里斯·特拉弗斯发现",
        origin: "存在于空气中，体积分数约为1/65000",
        funFacts: [
            "霓虹灯的名字来源于氖(Neon)",
            "氖在真空管中发出橙红色光",
            "液氖的制冷能力比液氢强3倍",
            "氖气在放电管中产生著名的橙红色辉光"
        ],
        history: "1898年拉姆齐和特拉弗斯在用液态空气分馏时发现了氖。他们将其命名为'Neon'，源自希腊语'neos'，意为'新的'。1910年法国工程师乔治·克劳德发明了第一个霓虹灯。",
        description: "发出橙红色光，用于霓虹灯"
    },
    {
        symbol: "Na",
        englishName: "Sodium",
        chineseName: "钠",
        type: "单质",
        atomicNumber: "11",
        atomicWeight: "22.990",
        formula: "Na",
        molecularWeight: "22.990",
        category: "碱金属",
        phase: "固体",
        state: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "强碱性",
        discovery: "1807年由英国化学家汉弗莱·戴维通过电解法发现",
        origin: "主要以岩盐(NaCl)形式存在，海水中含量丰富",
        funFacts: [
            "钠与水反应会放出氢气并产生氢氧化钠",
            "钠离子是维持人体电解质平衡的重要离子",
            "钠灯发出的黄光用于路灯照明",
            "钠的化合物如食盐是人类最早使用的化学品之一"
        ],
        history: "虽然钠的化合物自古以来就被使用，但金属钠直到1807年才由戴维通过电解熔融的氢氧化钠首次分离得到。钠的名字来自拉丁文'natrium'，来自埃及的硝石。",
        description: "活泼金属，与水剧烈反应"
    },
    {
        symbol: "Mg",
        englishName: "Magnesium",
        chineseName: "镁",
        type: "单质",
        atomicNumber: "12",
        atomicWeight: "24.305",
        formula: "Mg",
        molecularWeight: "24.305",
        category: "碱土金属",
        phase: "固体",
        state: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "碱性",
        discovery: "1808年由英国化学家汉弗莱·戴维发现",
        origin: "主要从菱镁矿(MgCO₃)和白云石中提取，海水也是重要来源",
        funFacts: [
            "镁燃烧时发出耀眼的白光，曾用于闪光灯",
            "是人体必需的矿物质，参与300多种酶反应",
            "镁合金比铝还轻，用于飞机和汽车制造",
            "叶绿素分子中含有镁离子"
        ],
        history: "1808年戴维通过电解氧化镁和氧化汞的混合物发现了镁。镁的名字来自希腊地名'Magnesia'。19世纪主要用于烟火和冶金，20世纪开始在航空航天领域广泛应用。",
        description: "轻质金属，燃烧时发出耀眼白光"
    },
    {
        symbol: "Al",
        englishName: "Aluminum",
        chineseName: "铝",
        type: "单质",
        atomicNumber: "13",
        atomicWeight: "26.982",
        formula: "Al",
        molecularWeight: "26.982",
        category: "金属",
        phase: "固体",
        state: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "两性",
        discovery: "1825年由丹麦化学家汉斯·克里斯蒂安·奥斯特德发现",
        origin: "主要以铝土矿形式存在，是地壳中含量第三多的元素",
        funFacts: [
            "曾比黄金还珍贵，拿破仑用铝餐具招待贵宾",
            "铝的密度只有钢的1/3，强度却很高",
            "铝罐回收再利用可节约95%的能源",
            "氧化铝膜使铝具有优良的耐腐蚀性"
        ],
        history: "1825年奥斯特德首次分离出不纯的铝。1886年美国化学家查尔斯·马丁·霍尔和法国化学家保罗·埃鲁分别独立发明了电解制铝法，使铝得以大规模生产，价格大幅下降。",
        description: "最丰富的金属元素，质轻耐腐蚀"
    },
    {
        symbol: "Si",
        englishName: "Silicon",
        chineseName: "硅",
        type: "单质",
        atomicNumber: "14",
        atomicWeight: "28.086",
        formula: "Si",
        molecularWeight: "28.086",
        category: "准金属",
        phase: "固体",
        state: "固体",
        color: "灰色",
        odor: "无味",
        acidBase: "酸性",
        discovery: "1824年由瑞典化学家约恩斯·雅各布·贝采利乌斯发现",
        origin: "主要以二氧化硅和硅酸盐形式存在，占地壳质量的27.7%",
        funFacts: [
            "硅是地壳中第二多的元素",
            "硅芯片是现代计算机的核心",
            "硅太阳能电池是最主要的光伏技术",
            "硅酮聚合物广泛用于医疗和日用品"
        ],
        history: "1811年盖-吕萨克和泰纳尔可能制备出不纯的硅，但通常认为1824年贝采利乌斯首次分离出较纯的硅。20世纪50年代，随着晶体管的发明，硅成为信息时代的基石材料。",
        description: "半导体工业的基础材料"
    },
    {
        symbol: "P",
        englishName: "Phosphorus",
        chineseName: "磷",
        type: "单质",
        atomicNumber: "15",
        atomicWeight: "30.974",
        formula: "P",
        molecularWeight: "30.974",
        category: "非金属",
        phase: "固体",
        state: "固体",
        color: "白色",
        odor: "刺激性",
        acidBase: "酸性",
        discovery: "1669年由德国炼金术士亨宁·布兰德发现",
        origin: "主要以磷酸盐矿物形式存在，如磷酸钙，是生命必需元素",
        funFacts: [
            "是第一个被发现的元素，虽然不是金属",
            "白磷在空气中会自燃，必须保存在水中",
            "DNA和RNA分子中含有磷酸基团",
            "磷是骨骼和牙齿的重要组成元素"
        ],
        history: "1669年布兰德通过蒸馏人尿意外发现了磷，这是第一个被确认的化学元素。磷的名字来自希腊语'phosphoros'，意为'光的携带者'。19世纪开始大规模开采磷矿用于肥料生产。",
        description: "生命必需元素，有白磷和红磷两种同素异形体"
    },
    {
        symbol: "S",
        englishName: "Sulfur",
        chineseName: "硫",
        type: "单质",
        atomicNumber: "16",
        atomicWeight: "32.065",
        formula: "S",
        molecularWeight: "32.065",
        category: "非金属",
        phase: "固体",
        state: "固体",
        color: "黄色",
        odor: "刺激性",
        acidBase: "酸性",
        discovery: "古代已知，1777年拉瓦锡确认为元素",
        origin: "以单质硫和硫化物矿物形式存在，火山活动地区丰富",
        funFacts: [
            "硫磺在古印度和中国被用于药物和宗教仪式",
            "硫是蛋白质和某些氨基酸的重要组成元素",
            "硫酸被称为'化学工业之母'",
            "硫化橡胶的发明彻底改变了橡胶工业"
        ],
        history: "硫是人类最早认识的化学元素之一，古代文明中广泛用于熏蒸消毒、火药制造和宗教仪式。1777年拉瓦锡证明硫是一种元素。19世纪随着接触法制硫酸的发明，硫成为现代化学工业的重要基础原料。",
        description: "黄色固体，有刺激性气味"
    },
    {
        symbol: "Cl",
        englishName: "Chlorine",
        chineseName: "氯",
        type: "单质",
        atomicNumber: "17",
        atomicWeight: "35.453",
        formula: "Cl",
        molecularWeight: "35.453",
        category: "卤素",
        phase: "气体",
        state: "气体",
        color: "黄绿色",
        odor: "刺激性",
        acidBase: "酸性",
        discovery: "1774年由瑞典化学家卡尔·威尔海姆·舍勒发现",
        origin: "主要以岩盐(NaCl)形式存在于海水和矿床中",
        funFacts: [
            "氯气在第一次世界大战中被用作化学武器",
            "氯是漂白剂和消毒剂的主要成分",
            "人体胃液中含有盐酸",
            "氯氟烃(CFCs)曾经广泛用作制冷剂"
        ],
        history: "1774年舍勒通过盐酸与二氧化锰反应首次制得氯气，但误认为是含氧的化合物。1810年戴维证明氯是一种元素。1831年英国发明家查尔斯·坦南特发明了漂白粉，开启了氯的工业化应用。",
        description: "黄绿色有毒气体，强氧化剂"
    },
    {
        symbol: "Ar",
        englishName: "Argon",
        chineseName: "氩",
        type: "单质",
        atomicNumber: "18",
        atomicWeight: "39.948",
        formula: "Ar",
        molecularWeight: "39.948",
        category: "稀有气体",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1894年由英国科学家约翰·威廉·斯特拉特·瑞利和威廉·拉姆齐发现",
        origin: "占空气体积的0.93%，是空气中第三多的气体",
        funFacts: [
            "氩的名字来自希腊语'argos'，意为'懒惰的'",
            "白炽灯泡中充填氩气可延长灯丝寿命",
            "氩弧焊是现代工业重要的焊接技术",
            "氩在地球大气中的含量比二氧化碳高20多倍"
        ],
        history: "1894年瑞利和拉姆齐通过精确测定氮气的密度差异发现了氩。这是第一个被发现的稀有气体，开启了稀有气体研究的新纪元。氩的化学惰性使其在工业上有重要应用价值。",
        description: "惰性气体，用于保护气氛"
    },

    // 常见化合物
    {
        symbol: "H₂O",
        englishName: "Water",
        chineseName: "水",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "H₂O",
        molecularWeight: "18.015",
        category: "无机化合物",
        phase: "液体",
        state: "液体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "自古已知，化学组成由卡文迪什和拉瓦锡在18世纪确定",
        origin: "地球表面71%被水覆盖，大气水循环产生淡水",
        funFacts: [
            "水在4°C时密度最大",
            "水分子呈V形结构，键角104.5°",
            "地球上的水已有45亿年历史",
            "人体重量的60%是水"
        ],
        history: "古代哲学家认为水是四大元素之一。1781年卡文迪什证明水是氢和氧的化合物，推翻了水是元素的传统观念。",
        description: "生命之源，优良的溶剂，沸点100°C，冰点0°C，表面张力大"
    },
    {
        symbol: "CO₂",
        englishName: "Carbon Dioxide",
        chineseName: "二氧化碳",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "CO₂",
        molecularWeight: "44.009",
        category: "无机化合物",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "酸性氧化物",
        discovery: "1754年由英国化学家约瑟夫·布莱克发现",
        origin: "生物呼吸、燃烧和发酵产生，大气中含量约为0.04%",
        funFacts: [
            "植物光合作用的原料",
            "干冰是固态二氧化碳，升华温度为-78.5°C",
            "是主要的温室气体之一",
            "碳酸饮料中的气泡就是二氧化碳"
        ],
        history: "1754年布莱克首次发现并命名二氧化碳。18世纪末拉瓦锡证明其为碳的氧化物。19世纪开始工业化生产，用于食品和工业。",
        description: "植物光合作用原料，干冰为固态，温室效应气体"
    },
    {
        symbol: "NaCl",
        englishName: "Sodium Chloride",
        chineseName: "氯化钠",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "NaCl",
        molecularWeight: "58.443",
        category: "无机盐",
        phase: "固体",
        state: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "中性盐",
        discovery: "古代已知，化学组成由拉瓦锡在18世纪确定",
        origin: "主要从海水晒盐和岩盐矿开采获得，地球海洋中储量巨大",
        funFacts: [
            "人类使用食盐已有数千年历史",
            "是人体必需的电解质",
            "古代用盐腌制食物保存",
            "罗马士兵曾用盐作为部分军饷",
            "死海的盐分浓度是普通海水的8倍"
        ],
        history: "食盐的使用可追溯到史前时期，约公元前6000年开始。古代文明中盐是极其珍贵的商品，曾作为货币使用。18世纪拉瓦锡确定了其化学组成。现代通过海水晒盐和矿盐开采获得，是最重要的化工原料之一。",
        description: "白色晶体，易溶于水，是人体必需电解质，重要的调味品和防腐剂"
    },
    {
        symbol: "CH₄",
        englishName: "Methane",
        chineseName: "甲烷",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "CH₄",
        molecularWeight: "16.043",
        category: "有机化合物",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1776年由意大利物理学家亚历山德罗·伏打发现",
        origin: "天然气田、沼气、反刍动物消化过程和垃圾填埋场产生",
        funFacts: [
            "是天然气的主要成分，占70-90%",
            "温室效应是二氧化碳的25倍",
            "天然气水合物称为可燃冰",
            "沼气池发酵产生甲烷作为燃料",
            "火星大气中也检测到了甲烷"
        ],
        history: "1776年伏打通过沼泽气体实验发现了甲烷。19世纪开始用于照明和取暖。20世纪随着天然气工业的发展，甲烷成为重要能源。现代通过页岩气革命和可燃冰开采，甲烷资源储量大幅增加。",
        description: "无色无味气体，最简单的烃类，天然气主要成分，重要燃料和化工原料"
    },
    {
        symbol: "NH₃",
        englishName: "Ammonia",
        chineseName: "氨",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "NH₃",
        molecularWeight: "17.031",
        category: "无机化合物",
        phase: "气体",
        state: "气体",
        color: "无色",
        odor: "刺激性",
        acidBase: "弱碱性",
        discovery: "1774年由英国化学家约瑟夫·普利斯特里分离得到",
        origin: "通过哈伯法由氮气和氢气合成，也存在于自然界和生物代谢中",
        funFacts: [
            "是工业上最重要的化学品之一",
            "液氨用作制冷剂",
            "氨水是常用的清洁剂",
            "人体尿液中含有微量氨",
            "氨与酸反应生成铵盐"
        ],
        history: "1774年普利斯特里通过加热氯化铵和熟石灰制得氨气。1785年法国化学家克劳德·贝托莱确定了其组成。1909年哈伯发明合成氨法，使大规模生产成为可能，推动了现代农业发展。",
        description: "无色有刺激性气味的气体，易溶于水，是重要的化工原料和肥料"
    },
    {
        symbol: "C₂H₅OH",
        englishName: "Ethanol",
        chineseName: "乙醇",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "C₂H₅OH",
        molecularWeight: "46.069",
        category: "有机化合物",
        phase: "液体",
        state: "液体",
        color: "无色",
        odor: "特殊香味",
        acidBase: "中性",
        discovery: "古代通过发酵制得，化学组成由拉瓦锡在18世纪确定",
        origin: "通过糖类发酵或乙烯水合制备，天然存在于发酵水果和酒精饮料中",
        funFacts: [
            "是酒精饮料的主要成分",
            "75%乙醇溶液消毒效果最好",
            "乙醇汽油用作汽车燃料",
            "无水乙醇称为绝对酒精",
            "人体肝脏可以代谢乙醇"
        ],
        history: "酒精的制取和使用可以追溯到史前时期，古代各文明都掌握了发酵制酒技术。18世纪拉瓦锡确定了其化学组成。19世纪开始工业化生产，20世纪用于燃料和化工原料。现代通过发酵和水合工艺大规模生产。",
        description: "无色液体，有特殊香味，易挥发和燃烧，是酒精的主要成分"
    },
    {
        symbol: "H₂SO₄",
        englishName: "Sulfuric Acid",
        chineseName: "硫酸",
        type: "化合物",
        atomicNumber: "",
        atomicWeight: "",
        formula: "H₂SO₄",
        molecularWeight: "98.079",
        category: "无机酸",
        phase: "液体",
        state: "液体",
        color: "无色",
        odor: "刺激性",
        acidBase: "强酸性",
        discovery: "8世纪波斯炼金术士贾比尔发现，18世纪拉瓦锡确定组成",
        origin: "通过接触法从硫磺或硫化物矿制备",
        funFacts: [
            "被称为'化学工业之母'",
            "浓硫酸有强脱水性和吸水性",
            "与金属反应产生氢气",
            "古代用于制造肥料和炸药"
        ],
        history: "古代被称为'矾油'，800年左右波斯炼金术士贾比尔首次制得。1831年英国化学家菲利普斯发明接触法，实现工业化生产。",
        description: "无色油状液体，强腐蚀性，工业上最重要的化学品之一"
    }
];

// 导出数据供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = chemicalData;
}