// 化学元素和化合物数据
const chemicalData = [
    // 元素周期表主族元素
    {
        symbol: "H",
        englishName: "Hydrogen",
        chineseName: "氢",
        type: "单质",
        atomicNumber: 1,
        atomicWeight: 1.008,
        category: "非金属",
        phase: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1766年由亨利·卡文迪什发现",
        origin: "宇宙大爆炸产生，地球上主要来自水和碳氢化合物",
        funFacts: [
            "占宇宙质量的75%",
            "太阳的能量来源于氢核聚变",
            "液氢是火箭燃料的主要成分",
            "氢气球曾用于早期航空"
        ],
        history: "氢气最早由帕拉塞尔苏斯无意中发现，但直到1766年才被卡文迪什确认为独立元素。法国化学家拉瓦锡将其命名为'Hydrogen'，意为'水生成者'。",
        description: "宇宙中最丰富的元素，最轻的气体，易燃易爆"
    },
    {
        symbol: "He",
        englishName: "Helium",
        chineseName: "氦",
        type: "单质",
        atomicNumber: 2,
        atomicWeight: 4.003,
        category: "稀有气体",
        phase: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1868年由皮埃尔·詹森和诺曼·洛克耶发现",
        origin: "主要来自天然气井中的放射性衰变产物",
        funFacts: [
            "在太阳日珥的光谱中首次发现",
            "液氦在-271°C以下会变成超流体",
            "人类声音在氦气中会变尖",
            "氦气是目前唯一无法固化的元素"
        ],
        history: "1868年日食期间，法国天文学家詹森和英国天文学家洛克耶同时在太阳光谱中发现未知黄色谱线，洛克耶将其命名为'Helium'，意为'太阳'。直到1895年才被拉姆齐在地球上发现。",
        description: "最轻的惰性气体，不能燃烧，用于填充气球和飞艇"
    },
    {
        symbol: "Li",
        englishName: "Lithium",
        chineseName: "锂",
        type: "单质",
        atomicNumber: 3,
        atomicWeight: 6.941,
        category: "碱金属",
        discovery: "1817年由瑞典化学家约翰·奥古斯特·阿尔弗韦德松发现",
        origin: "主要从锂辉石和盐湖卤水中提取，地壳中含量约为0.0065%",
        funFacts: [
            "是最轻的金属，密度只有水的一半",
            "锂电池为现代电子设备提供动力",
            "在核聚变反应中用作氚的生产原料",
            "某些锂化合物用于治疗躁郁症"
        ],
        history: "1817年瑞典化学家阿尔弗韦德松在分析透锂长石时发现了锂。1821年英国化学家威廉·托马斯·布兰德通过电解氯化锂首次分离出金属锂。20世纪后期，随着锂电池技术的发展，锂成为重要的战略资源。",
        description: "最轻的金属，用于锂电池"
    },
    {
        symbol: "Be",
        englishName: "Beryllium",
        chineseName: "铍",
        type: "单质",
        atomicNumber: 4,
        atomicWeight: 9.012,
        category: "碱土金属",
        discovery: "1798年由法国化学家路易-尼古拉·沃克兰发现",
        origin: "主要从绿柱石矿物中提取，地壳中含量约为0.0002%",
        funFacts: [
            "比钢还硬但重量只有铝的1/3",
            "用于航天器结构材料和卫星反射镜",
            "具有优良的X射线透射性",
            "吸入铍粉尘会导致严重的铍肺病"
        ],
        history: "1798年法国化学家沃克兰在分析绿柱石和祖母绿时发现了铍。1828年德国化学家弗里德里希·维勒和法国化学家安托万·比西分别独立地通过还原氯化铍分离出金属铍。20世纪40年代开始用于核工业和航空航天领域。",
        description: "轻质高强度金属，用于航空航天"
    },
    {
        symbol: "B",
        englishName: "Boron",
        chineseName: "硼",
        type: "单质",
        atomicNumber: 5,
        atomicWeight: 10.811,
        category: "准金属",
        discovery: "1808年由英国化学家戴维和法国化学家盖-吕萨克、泰纳尔分别独立发现",
        origin: "主要从硼砂和硼酸矿中提取，地壳中含量约为0.001%",
        funFacts: [
            "硼纤维比钢还强韧但重量很轻",
            "硼玻璃具有优良的耐热性和化学稳定性",
            "硼酸是天然的杀虫剂和防腐剂",
            "硼中子俘获疗法用于治疗脑肿瘤"
        ],
        history: "1808年英国化学家戴维和法国化学家盖-吕萨克、泰纳尔几乎同时通过还原硼酸发现了硼。19世纪主要用作清洁剂和防腐剂，20世纪随着硼纤维和硼合金的发展，成为重要的工业材料。",
        description: "硬度仅次于金刚石，用于制造硼玻璃"
    },
    {
        symbol: "C",
        englishName: "Carbon",
        chineseName: "碳",
        type: "单质",
        atomicNumber: 6,
        atomicWeight: 12.011,
        category: "非金属",
        discovery: "古代已知，1789年拉瓦锡确认为元素",
        origin: "宇宙中第四多的元素，地球上以石墨、金刚石、煤等形式存在",
        funFacts: [
            "碳的同素异形体包括金刚石、石墨、富勒烯、石墨烯等",
            "所有已知生命都基于碳化学",
            "大气中的CO₂是碳循环的重要组成部分",
            "石墨烯是已知最薄的材料，只有一个原子厚"
        ],
        history: "碳自古就被人类认识和使用，以木炭、煤和石墨的形式存在。1789年拉瓦锡通过实验证明金刚石和石墨都是由碳组成，推翻了金刚石是特殊物质的观念。现代化学的发展使碳成为理解有机化学和生命科学的中心元素。",
        description: "构成生命的基础元素，多种同素异形体"
    },
    {
        symbol: "N",
        englishName: "Nitrogen",
        chineseName: "氮",
        type: "单质",
        atomicNumber: 7,
        atomicWeight: 14.007,
        category: "非金属",
        discovery: "1772年由苏格兰化学家丹尼尔·卢瑟福发现",
        origin: "占空气体积的78%，是蛋白质和核酸的组成元素",
        funFacts: [
            "氮气在常温下化学性质很不活泼",
            "液氮的沸点为-196°C，常用于低温保存",
            "氮循环是地球生态系统的重要过程",
            "氮气可用于食品包装的惰性保护气体"
        ],
        history: "1772年卢瑟福通过实验发现了氮气，他称之为'有害空气'。法国化学家拉瓦锡在1789年将其命名为'azote'，意为'无生命'。后来发现氮是蛋白质的重要组成部分，对生命至关重要。",
        description: "空气中含量最多的气体，惰性"
    },
    {
        symbol: "O",
        englishName: "Oxygen",
        chineseName: "氧",
        type: "单质",
        atomicNumber: 8,
        atomicWeight: 15.999,
        category: "非金属",
        discovery: "1774年由英国化学家约瑟夫·普利斯特里和瑞典化学家卡尔·威尔海姆·舍勒独立发现",
        origin: "占空气体积的21%，是水和大多数氧化物的组成元素",
        funFacts: [
            "氧气是地球大气中第二多的气体",
            "臭氧(O₃)是氧的同素异形体，保护地球免受紫外线伤害",
            "液氧呈淡蓝色，用作火箭燃料的氧化剂",
            "高压氧疗法用于治疗一氧化碳中毒"
        ],
        history: "1774年普利斯特里通过加热氧化汞制得氧气，舍勒在1772年也独立发现了氧气。拉瓦锡在1775年通过实验证明氧气是空气的一个组成部分，并推翻了燃素说。",
        description: "支持燃烧和呼吸的气体"
    },
    {
        symbol: "F",
        englishName: "Fluorine",
        chineseName: "氟",
        type: "单质",
        atomicNumber: 9,
        atomicWeight: 18.998,
        category: "卤素",
        discovery: "1886年由法国化学家亨利·莫瓦桑首次分离",
        origin: "以萤石(CaF₂)和冰晶石(Na₃AlF₆)形式存在，地壳中含量约为0.065%",
        funFacts: [
            "是已知最活泼的非金属元素",
            "氟化水可以预防龋齿",
            "聚四氟乙烯(特氟龙)含有氟原子",
            "大气中的氟利昂曾经是臭氧层破坏的主要原因"
        ],
        history: "虽然氟的化合物早已为人所知，但单质氟的分离极其困难。1886年法国化学家莫瓦桑通过电解氟化氢钾首次制得氟气，为此获得了1906年诺贝尔化学奖。",
        description: "最活泼的非金属元素，剧毒"
    },
    {
        symbol: "Ne",
        englishName: "Neon",
        chineseName: "氖",
        type: "单质",
        atomicNumber: 10,
        atomicWeight: 20.180,
        category: "稀有气体",
        discovery: "1898年由英国化学家威廉·拉姆齐和莫里斯·特拉弗斯发现",
        origin: "存在于空气中，体积分数约为1/65000",
        funFacts: [
            "霓虹灯的名字来源于氖(Neon)",
            "氖在真空管中发出橙红色光",
            "液氖的制冷能力比液氢强3倍",
            "氖气在放电管中产生著名的橙红色辉光"
        ],
        history: "1898年拉姆齐和特拉弗斯在用液态空气分馏时发现了氖。他们将其命名为'Neon'，源自希腊语'neos'，意为'新的'。1910年法国工程师乔治·克劳德发明了第一个霓虹灯。",
        description: "发出橙红色光，用于霓虹灯"
    },
    {
        symbol: "Na",
        englishName: "Sodium",
        chineseName: "钠",
        type: "单质",
        atomicNumber: 11,
        atomicWeight: 22.990,
        category: "碱金属",
        discovery: "1807年由英国化学家汉弗莱·戴维通过电解法发现",
        origin: "主要以岩盐(NaCl)形式存在，海水中含量丰富",
        funFacts: [
            "钠与水反应会放出氢气并产生氢氧化钠",
            "钠离子是维持人体电解质平衡的重要离子",
            "钠灯发出的黄光用于路灯照明",
            "钠的化合物如食盐是人类最早使用的化学品之一"
        ],
        history: "虽然钠的化合物自古以来就被使用，但金属钠直到1807年才由戴维通过电解熔融的氢氧化钠首次分离得到。钠的名字来自拉丁文'natrium'，来自埃及的硝石。",
        description: "活泼金属，与水剧烈反应"
    },
    {
        symbol: "Mg",
        englishName: "Magnesium",
        chineseName: "镁",
        type: "单质",
        atomicNumber: 12,
        atomicWeight: 24.305,
        category: "碱土金属",
        discovery: "1808年由英国化学家汉弗莱·戴维发现",
        origin: "主要从菱镁矿(MgCO₃)和白云石中提取，海水也是重要来源",
        funFacts: [
            "镁燃烧时发出耀眼的白光，曾用于闪光灯",
            "是人体必需的矿物质，参与300多种酶反应",
            "镁合金比铝还轻，用于飞机和汽车制造",
            "叶绿素分子中含有镁离子"
        ],
        history: "1808年戴维通过电解氧化镁和氧化汞的混合物发现了镁。镁的名字来自希腊地名'Magnesia'。19世纪主要用于烟火和冶金，20世纪开始在航空航天领域广泛应用。",
        description: "轻质金属，燃烧时发出耀眼白光"
    },
    {
        symbol: "Al",
        englishName: "Aluminum",
        chineseName: "铝",
        type: "单质",
        atomicNumber: 13,
        atomicWeight: 26.982,
        category: "金属",
        phase: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "两性",
        discovery: "1825年由丹麦化学家汉斯·克里斯蒂安·奥斯特德发现",
        origin: "主要以铝土矿形式存在，是地壳中含量第三多的元素",
        funFacts: [
            "曾比黄金还珍贵，拿破仑用铝餐具招待贵宾",
            "铝的密度只有钢的1/3，强度却很高",
            "铝罐回收再利用可节约95%的能源",
            "氧化铝膜使铝具有优良的耐腐蚀性"
        ],
        history: "1825年奥斯特德首次分离出不纯的铝。1886年美国化学家查尔斯·马丁·霍尔和法国化学家保罗·埃鲁分别独立发明了电解制铝法，使铝得以大规模生产，价格大幅下降。",
        description: "最丰富的金属元素，质轻耐腐蚀"
    },
    {
        symbol: "Si",
        englishName: "Silicon",
        chineseName: "硅",
        type: "单质",
        atomicNumber: 14,
        atomicWeight: 28.086,
        category: "准金属",
        discovery: "1824年由瑞典化学家约恩斯·雅各布·贝采利乌斯发现",
        origin: "主要以二氧化硅和硅酸盐形式存在，占地壳质量的27.7%",
        funFacts: [
            "硅是地壳中第二多的元素",
            "硅芯片是现代计算机的核心",
            "硅太阳能电池是最主要的光伏技术",
            "硅酮聚合物广泛用于医疗和日用品"
        ],
        history: "1811年盖-吕萨克和泰纳尔可能制备出不纯的硅，但通常认为1824年贝采利乌斯首次分离出较纯的硅。20世纪50年代，随着晶体管的发明，硅成为信息时代的基石材料。",
        description: "半导体工业的基础材料"
    },
    {
        symbol: "P",
        englishName: "Phosphorus",
        chineseName: "磷",
        type: "单质",
        atomicNumber: 15,
        atomicWeight: 30.974,
        category: "非金属",
        discovery: "1669年由德国炼金术士亨宁·布兰德发现",
        origin: "主要以磷酸盐矿物形式存在，如磷酸钙，是生命必需元素",
        funFacts: [
            "是第一个被发现的元素，虽然不是金属",
            "白磷在空气中会自燃，必须保存在水中",
            "DNA和RNA分子中含有磷酸基团",
            "磷是骨骼和牙齿的重要组成元素"
        ],
        history: "1669年布兰德通过蒸馏人尿意外发现了磷，这是第一个被确认的化学元素。磷的名字来自希腊语'phosphoros'，意为'光的携带者'。19世纪开始大规模开采磷矿用于肥料生产。",
        description: "生命必需元素，有白磷和红磷两种同素异形体"
    },
    {
        symbol: "S",
        englishName: "Sulfur",
        chineseName: "硫",
        type: "单质",
        atomicNumber: 16,
        atomicWeight: 32.065,
        category: "非金属",
        discovery: "古代已知，1777年拉瓦锡确认为元素",
        origin: "以单质硫和硫化物矿物形式存在，火山活动地区丰富",
        funFacts: [
            "硫磺在古印度和中国被用于药物和宗教仪式",
            "硫是蛋白质和某些氨基酸的重要组成元素",
            "硫酸被称为'化学工业之母'",
            "硫化橡胶的发明彻底改变了橡胶工业"
        ],
        history: "硫是人类最早认识的化学元素之一，古代文明中广泛用于熏蒸消毒、火药制造和宗教仪式。1777年拉瓦锡证明硫是一种元素。19世纪随着接触法制硫酸的发明，硫成为现代化学工业的重要基础原料。",
        description: "黄色固体，有刺激性气味"
    },
    {
        symbol: "Cl",
        englishName: "Chlorine",
        chineseName: "氯",
        type: "单质",
        atomicNumber: 17,
        atomicWeight: 35.453,
        category: "卤素",
        discovery: "1774年由瑞典化学家卡尔·威尔海姆·舍勒发现",
        origin: "主要以岩盐(NaCl)形式存在于海水和矿床中",
        funFacts: [
            "氯气在第一次世界大战中被用作化学武器",
            "氯是漂白剂和消毒剂的主要成分",
            "人体胃液中含有盐酸",
            "氯氟烃(CFCs)曾经广泛用作制冷剂"
        ],
        history: "1774年舍勒通过盐酸与二氧化锰反应首次制得氯气，但误认为是含氧的化合物。1810年戴维证明氯是一种元素。1831年英国发明家查尔斯·坦南特发明了漂白粉，开启了氯的工业化应用。",
        description: "黄绿色有毒气体，强氧化剂"
    },
    {
        symbol: "Ar",
        englishName: "Argon",
        chineseName: "氩",
        type: "单质",
        atomicNumber: 18,
        atomicWeight: 39.948,
        category: "稀有气体",
        discovery: "1894年由英国科学家约翰·威廉·斯特拉特·瑞利和威廉·拉姆齐发现",
        origin: "占空气体积的0.93%，是空气中第三多的气体",
        funFacts: [
            "氩的名字来自希腊语'argos'，意为'懒惰的'",
            "白炽灯泡中充填氩气可延长灯丝寿命",
            "氩弧焊是现代工业重要的焊接技术",
            "氩在地球大气中的含量比二氧化碳高20多倍"
        ],
        history: "1894年瑞利和拉姆齐通过精确测定氮气的密度差异发现了氩。这是第一个被发现的稀有气体，开启了稀有气体研究的新纪元。氩的化学惰性使其在工业上有重要应用价值。",
        description: "惰性气体，用于保护气氛"
    },
    {
        symbol: "K",
        englishName: "Potassium",
        chineseName: "钾",
        type: "单质",
        atomicNumber: 19,
        atomicWeight: 39.098,
        category: "碱金属",
        phase: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "强碱性",
        discovery: "1807年由英国化学家汉弗莱·戴维通过电解法发现",
        origin: "主要从钾盐矿物如钾石盐(KCl)中提取，地壳中含量约为2.1%",
        funFacts: [
            "是动植物必需的营养元素",
            "钾离子是维持人体电解质平衡的重要离子",
            "钾钠合金用作核反应堆的冷却剂",
            "钾的化合物如硝酸钾是重要肥料",
            "钾在水中反应剧烈，产生紫色火焰"
        ],
        history: "虽然钾的化合物自古以来就被使用，但金属钾直到1807年才由戴维通过电解熔融的氢氧化钾首次分离得到。钾的名字来自英文'potash'，意为'草木灰'。19世纪开始用于肥料，20世纪发现其对生物的重要性。",
        description: "活泼金属，与水剧烈反应，对动植物生长至关重要"
    },
    {
        symbol: "Ca",
        englishName: "Calcium",
        chineseName: "钙",
        type: "单质",
        atomicNumber: 20,
        atomicWeight: 40.078,
        category: "碱土金属",
        phase: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "碱性",
        discovery: "1808年由英国化学家汉弗莱·戴维通过电解法发现",
        origin: "主要以石灰石(CaCO₃)和石膏(CaSO₄·2H₂O)形式存在，地壳中含量约为3.6%",
        funFacts: [
            "是人体中含量最多的矿物质",
            "钙离子参与肌肉收缩和神经传导",
            "石灰石的主要成分就是碳酸钙",
            "钙的火焰呈橙红色",
            "珊瑚礁和贝壳的主要成分是碳酸钙"
        ],
        history: "钙的化合物自古以来就被广泛使用，1808年戴维通过电解氧化钙和氧化汞的混合物首次分离出金属钙。钙的名字来自拉丁文'calx'，意为'石灰'。19世纪开始工业化生产，现代用于合金和还原剂。",
        description: "银白色金属，构成骨骼和牙齿的主要成分，是生命必需元素"
    },
    {
        symbol: "Fe",
        englishName: "Iron",
        chineseName: "铁",
        type: "单质",
        atomicNumber: 26,
        atomicWeight: 55.845,
        category: "过渡金属",
        phase: "固体",
        color: "银白色至灰色",
        odor: "无味",
        acidBase: "两性",
        discovery: "古代已知，铁器时代约公元前1200年开始",
        origin: "地壳中含量第四多的元素，主要以赤铁矿(Fe₂O₃)和磁铁矿(Fe₃O₄)形式存在",
        funFacts: [
            "地核主要由铁和镍组成",
            "血红蛋白中的铁使血液呈红色",
            "铁是地壳中含量最多的金属元素",
            "不锈钢含有铁、铬、镍等元素",
            "铁锈是氧化铁的水合物"
        ],
        history: "铁是人类最早使用的金属之一，约公元前4000年已开始使用。铁器时代约公元前1200年开始，标志着人类文明的重要进步。工业革命期间，铁成为最重要的工业金属。现代钢铁工业是现代工业的基础。",
        description: "最重要的金属之一，地壳中含量最多的金属元素，血红蛋白的组成部分"
    },
    {
        symbol: "Cu",
        englishName: "Copper",
        chineseName: "铜",
        type: "单质",
        atomicNumber: 29,
        atomicWeight: 63.546,
        category: "过渡金属",
        phase: "固体",
        color: "红棕色",
        odor: "无味",
        acidBase: "弱碱性",
        discovery: "古代已知，约公元前8000年开始使用",
        origin: "主要以黄铜矿(CuFeS₂)和孔雀石(Cu₂CO₃(OH)₂)形式存在，地壳中含量约为0.0068%",
        funFacts: [
            "是人类最早使用的金属之一",
            "纯铜的导电性仅次于银",
            "铜绿是碱式碳酸铜的保护层",
            "青铜器时代约公元前3000年开始",
            "人体需要微量铜元素"
        ],
        history: "铜是人类最早使用的金属之一，约公元前8000年开始使用。青铜时代约公元前3000年开始，铜锡合金的使用推动了人类文明的发展。古代中国、埃及、希腊都广泛使用铜器。电气时代使铜成为最重要的导电材料。",
        description: "优良的导电导热性，红色金属，人类最早使用的金属之一"
    },
    {
        symbol: "Zn",
        englishName: "Zinc",
        chineseName: "锌",
        type: "单质",
        atomicNumber: 30,
        atomicWeight: 65.38,
        category: "过渡金属",
        phase: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "两性",
        discovery: "1746年由德国化学家安德烈亚斯·马格拉夫发现",
        origin: "主要以闪锌矿(ZnS)形式存在，地壳中含量约为0.0075%",
        funFacts: [
            "是人体必需的微量元素",
            "镀锌钢板称为白铁皮",
            "锌与铜形成黄铜合金",
            "干电池外壳就是锌制成的",
            "锌在空气中会形成致密的氧化膜"
        ],
        history: "锌的化合物自古为人所知，1746年德国化学家马格拉夫首次分离出金属锌。16世纪中国开始大规模使用锌币，18世纪开始用于黄铜制造，19世纪发明镀锌防腐技术，现代广泛应用于合金、电池和防腐领域。",
        description: "抗腐蚀性强的金属，银白色，广泛用于镀锌防锈"
    },
    {
        symbol: "Ag",
        englishName: "Silver",
        chineseName: "银",
        type: "单质",
        atomicNumber: 47,
        atomicWeight: 107.868,
        category: "过渡金属",
        phase: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "弱碱性",
        discovery: "古代已知，约公元前3000年开始使用",
        origin: "主要以辉银矿(Ag₂S)和角银矿(AgCl)形式存在，地壳中含量约为0.0000075%",
        funFacts: [
            "是导电性和导热性最好的金属",
            "银离子具有杀菌作用",
            "银器会变黑是因为与硫化氢反应",
            "古代用作货币和装饰品",
            "摄影术的发展离不开银盐"
        ],
        history: "银是人类最早使用的金属之一，约公元前3000年开始使用。古代文明都广泛使用银器，中国用银制作货币和装饰品。16世纪美洲银矿的发现改变了世界经济格局。19世纪摄影术的发明使银成为重要工业原料。现代用于电子、医疗和珠宝领域。",
        description: "导电性最好的金属，银白色有光泽，具有杀菌作用"
    },
    {
        symbol: "Au",
        englishName: "Gold",
        chineseName: "金",
        type: "单质",
        atomicNumber: 79,
        atomicWeight: 196.967,
        category: "过渡金属",
        phase: "固体",
        color: "金黄色",
        odor: "无味",
        acidBase: "惰性",
        discovery: "古代已知，约公元前4000年开始使用",
        origin: "主要以自然金形式存在，地壳中含量约为0.0000005%，也存在于石英脉中",
        funFacts: [
            "是延展性最好的金属，可打成金箔",
            "不受空气、水和大多数化学试剂腐蚀",
            "国际标准金纯度为24K",
            "太空服面罩镀有金膜防紫外线",
            "人体可以安全植入金制医疗器械"
        ],
        history: "金是人类最早使用的金属之一，约公元前4000年开始使用。古埃及人用金制作法老面具，中国古代用金制作精美工艺品。金作为货币和财富象征贯穿人类文明史。现代用于电子、医疗、航天和珠宝领域，是重要的贵金属和保值资产。",
        description: "贵金属，化学性质极其稳定，金黄色，延展性最好的金属"
    },
    {
        symbol: "Hg",
        englishName: "Mercury",
        chineseName: "汞",
        type: "单质",
        atomicNumber: 80,
        atomicWeight: 200.592,
        category: "过渡金属",
        phase: "液体",
        color: "银白色",
        odor: "无味",
        acidBase: "弱碱性",
        discovery: "古代已知，中国炼丹术士和希腊人使用",
        origin: "主要以辰砂(HgS)形式存在，地壳中含量约为0.000008%",
        funFacts: [
            "是常温下唯一的液态金属",
            "古代中国用于炼制长生不老药",
            "水银温度计利用其热胀冷缩性质",
            "在室温下会缓慢挥发",
            "汞齐可用于提取金银"
        ],
        history: "汞自古为人所知，中国炼丹术士和希腊人都使用汞。16世纪西班牙在美洲用汞提取金银，推动了全球贸易。18-19世纪用于温度计、气压计和医药。20世纪发现其毒性，逐步限制使用，现代主要用于工业催化剂和电气设备。",
        description: "常温下为液态的银白色金属，易挥发，有毒，用于温度计和工业"
    },
    {
        symbol: "Pb",
        englishName: "Lead",
        chineseName: "铅",
        type: "单质",
        atomicNumber: 82,
        atomicWeight: 207.2,
        category: "金属",
        phase: "固体",
        color: "蓝灰色",
        odor: "无味",
        acidBase: "两性",
        discovery: "古代已知，约公元前7000年开始使用",
        origin: "主要以方铅矿(PbS)形式存在，地壳中含量约为0.0013%",
        funFacts: [
            "罗马人用铅制作水管和酒器",
            "铅字印刷术推动了知识传播",
            "铅玻璃具有特殊的光学性质",
            "蓄电池使用铅作为电极材料",
            "铅中毒会影响神经系统发育"
        ],
        history: "铅是人类最早使用的金属之一，约公元前7000年开始使用。古埃及人用铅制作装饰品，罗马人广泛使用铅水管和酒器。中世纪用于制作彩色玻璃窗。16-19世纪用于印刷活字。现代主要用于蓄电池、防辐射材料和合金，但因其毒性逐步限制使用。",
        description: "密度大的蓝灰色金属，有毒，用于蓄电池和防辐射材料"
    },
    {
        symbol: "U",
        englishName: "Uranium",
        chineseName: "铀",
        type: "单质",
        atomicNumber: 92,
        atomicWeight: 238.029,
        category: "锕系金属",
        phase: "固体",
        color: "银白色",
        odor: "无味",
        acidBase: "两性",
        discovery: "1789年由德国化学家马丁·海因里希·克拉普罗特发现",
        origin: "主要以沥青铀矿(U₃O₈)和钒钾铀矿(K₂(UO₂)₂(VO₄)₂·3H₂O)形式存在",
        funFacts: [
            "是自然界最重的元素",
            "铀235是核裂变的主要材料",
            "铀238可转化为钚239用于核反应堆",
            "铀玻璃在紫外线下会发荧光",
            "天然铀中99.3%是铀238"
        ],
        history: "1789年克拉普罗特从沥青铀矿中发现了铀，并以天王星命名。1896年贝克勒尔发现铀的放射性，开创了原子时代。1942年费米建成第一个核反应堆。20世纪40年代曼哈顿计划用铀235制造原子弹，战后发展核电，成为重要能源。",
        description: "银白色放射性金属，最重的天然元素，核裂变燃料"
    },
    
    // 常见化合物
    {
        symbol: "H₂O",
        englishName: "Water",
        chineseName: "水",
        type: "化合物",
        formula: "H₂O",
        molecularWeight: 18.015,
        category: "无机化合物",
        phase: "液体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "自古已知，化学组成由卡文迪什和拉瓦锡在18世纪确定",
        origin: "地球表面71%被水覆盖，大气水循环产生淡水",
        funFacts: [
            "水在4°C时密度最大",
            "水分子呈V形结构，键角104.5°",
            "地球上的水已有45亿年历史",
            "人体重量的60%是水"
        ],
        history: "古代哲学家认为水是四大元素之一。1781年卡文迪什证明水是氢和氧的化合物，推翻了水是元素的传统观念。",
        description: "生命之源，优良的溶剂，沸点100°C，冰点0°C，表面张力大"
    },
    {
        symbol: "CO₂",
        englishName: "Carbon Dioxide",
        chineseName: "二氧化碳",
        type: "化合物",
        formula: "CO₂",
        molecularWeight: 44.009,
        category: "无机化合物",
        phase: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "酸性氧化物",
        state: "气体",
        description: "植物光合作用原料，干冰为固态，温室效应气体"
    },
    {
        symbol: "NaCl",
        englishName: "Sodium Chloride",
        chineseName: "氯化钠",
        type: "化合物",
        formula: "NaCl",
        molecularWeight: 58.443,
        category: "无机盐",
        phase: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "中性盐",
        discovery: "古代已知，化学组成由拉瓦锡在18世纪确定",
        origin: "主要从海水晒盐和岩盐矿开采获得，地球海洋中储量巨大",
        funFacts: [
            "人类使用食盐已有数千年历史",
            "是人体必需的电解质",
            "古代用盐腌制食物保存",
            "罗马士兵曾用盐作为部分军饷",
            "死海的盐分浓度是普通海水的8倍"
        ],
        history: "食盐的使用可追溯到史前时期，约公元前6000年开始。古代文明中盐是极其珍贵的商品，曾作为货币使用。18世纪拉瓦锡确定了其化学组成。现代通过海水晒盐和矿盐开采获得，是最重要的化工原料之一。",
        description: "白色晶体，易溶于水，是人体必需电解质，重要的调味品和防腐剂"
    },
    {
        symbol: "C₆H₁₂O₆",
        englishName: "Glucose",
        chineseName: "葡萄糖",
        type: "化合物",
        formula: "C₆H₁₂O₆",
        molecularWeight: 180.156,
        category: "有机化合物",
        phase: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1747年由德国化学家安德烈亚斯·马格拉夫从葡萄干中发现",
        origin: "广泛存在于水果、蜂蜜和植物汁液中，工业上通过淀粉水解制备",
        funFacts: [
            "是人体和动物的主要能量来源",
            "血糖就是指血液中的葡萄糖",
            "植物通过光合作用产生葡萄糖",
            "葡萄糖注射液用于医疗补液",
            "蜂蜜的主要成分就是葡萄糖和果糖"
        ],
        history: "1747年德国化学家马格拉夫从葡萄干中分离出葡萄糖。19世纪化学家确定了其结构。20世纪初开始工业化生产，成为最重要的糖类之一。现代通过玉米淀粉水解大规模生产，广泛应用于食品、医药和发酵工业。",
        description: "白色晶体，有甜味，易溶于水，是生物体的主要能量来源和单糖"
    },
    {
        symbol: "CH₄",
        englishName: "Methane",
        chineseName: "甲烷",
        type: "化合物",
        formula: "CH₄",
        molecularWeight: 16.043,
        category: "有机化合物",
        phase: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性",
        discovery: "1776年由意大利物理学家亚历山德罗·伏打发现",
        origin: "天然气田、沼气、反刍动物消化过程和垃圾填埋场产生",
        funFacts: [
            "是天然气的主要成分，占70-90%",
            "温室效应是二氧化碳的25倍",
            "天然气水合物称为可燃冰",
            "沼气池发酵产生甲烷作为燃料",
            "火星大气中也检测到了甲烷"
        ],
        history: "1776年伏打通过沼泽气体实验发现了甲烷。19世纪开始用于照明和取暖。20世纪随着天然气工业的发展，甲烷成为重要能源。现代通过页岩气革命和可燃冰开采，甲烷资源储量大幅增加。",
        description: "无色无味气体，最简单的烃类，天然气主要成分，重要燃料和化工原料"
    },
    {
        symbol: "NH₃",
        englishName: "Ammonia",
        chineseName: "氨",
        type: "化合物",
        formula: "NH₃",
        molecularWeight: 17.031,
        category: "无机化合物",
        phase: "气体",
        color: "无色",
        odor: "刺激性",
        acidBase: "弱碱性",
        discovery: "1774年由英国化学家约瑟夫·普利斯特里分离得到",
        origin: "通过哈伯法由氮气和氢气合成，也存在于自然界和生物代谢中",
        funFacts: [
            "是工业上最重要的化学品之一",
            "液氨用作制冷剂",
            "氨水是常用的清洁剂",
            "人体尿液中含有微量氨",
            "氨与酸反应生成铵盐"
        ],
        history: "1774年普利斯特里通过加热氯化铵和熟石灰制得氨气。1785年法国化学家克劳德·贝托莱确定了其组成。1909年哈伯发明合成氨法，使大规模生产成为可能，推动了现代农业发展。",
        description: "无色有刺激性气味的气体，易溶于水，是重要的化工原料和肥料"
    },
    {
        symbol: "C₂H₅OH",
        englishName: "Ethanol",
        chineseName: "乙醇",
        type: "化合物",
        formula: "C₂H₅OH",
        molecularWeight: 46.069,
        category: "有机化合物",
        phase: "液体",
        color: "无色",
        odor: "特殊香味",
        acidBase: "中性",
        discovery: "古代通过发酵制得，化学组成由拉瓦锡在18世纪确定",
        origin: "通过糖类发酵或乙烯水合制备，天然存在于发酵水果和酒精饮料中",
        funFacts: [
            "是酒精饮料的主要成分",
            "75%乙醇溶液消毒效果最好",
            "乙醇汽油用作汽车燃料",
            "无水乙醇称为绝对酒精",
            "人体肝脏可以代谢乙醇"
        ],
        history: "酒精的制取和使用可以追溯到史前时期，古代各文明都掌握了发酵制酒技术。18世纪拉瓦锡确定了其化学组成。19世纪开始工业化生产，20世纪用于燃料和化工原料。现代通过发酵和水合工艺大规模生产。",
        description: "无色液体，有特殊香味，易挥发和燃烧，是酒精的主要成分"
    },
    {
        symbol: "H₂SO₄",
        englishName: "Sulfuric Acid",
        chineseName: "硫酸",
        type: "化合物",
        formula: "H₂SO₄",
        molecularWeight: 98.079,
        category: "无机酸",
        phase: "液体",
        color: "无色",
        odor: "刺激性",
        acidBase: "强酸性",
        discovery: "8世纪波斯炼金术士贾比尔发现，18世纪拉瓦锡确定组成",
        origin: "通过接触法从硫磺或硫化物矿制备",
        funFacts: [
            "被称为'化学工业之母'",
            "浓硫酸有强脱水性和吸水性",
            "与金属反应产生氢气",
            "古代用于制造肥料和炸药"
        ],
        history: "古代被称为'矾油'，8世纪波斯炼金术士贾比尔首次制得。1831年英国化学家菲利普斯发明接触法，实现工业化生产。",
        description: "无色油状液体，强腐蚀性，工业上最重要的化学品之一"
    },
    {
        symbol: "CaCO₃",
        englishName: "Calcium Carbonate",
        chineseName: "碳酸钙",
        type: "化合物",
        formula: "CaCO₃",
        molecularWeight: 100.087,
        category: "无机盐",
        phase: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "碱性盐",
        discovery: "古代已知，18世纪拉瓦锡确定了其组成",
        origin: "天然存在于石灰石、大理石、白垩、贝壳和珊瑚中，也可通过工业合成制备",
        funFacts: [
            "是地壳中含量第四多的矿物",
            "珊瑚礁的主要成分就是碳酸钙",
            "蛋壳中95%的成分是碳酸钙",
            "钟乳石和石笋的主要成分",
            "在工业上用于制造水泥和石灰"
        ],
        history: "碳酸钙的使用可以追溯到史前时期，古埃及人用石灰石建造金字塔，古希腊人用大理石建造神庙。18世纪化学家拉瓦锡通过实验确定了碳酸钙的化学组成。19世纪工业革命期间，碳酸钙开始大规模开采，用于建筑、造纸和化工行业。",
        description: "白色固体，不溶于水，遇酸产生二氧化碳，是石灰石和大理石的主要成分"
    },
    {
        symbol: "O₃",
        englishName: "Ozone",
        chineseName: "臭氧",
        type: "化合物",
        formula: "O₃",
        molecularWeight: 47.998,
        category: "无机化合物",
        phase: "气体",
        color: "淡蓝色",
        odor: "特殊气味",
        acidBase: "中性",
        discovery: "1839年由德国化学家克里斯蒂安·弗里德里希·舍恩拜因发现",
        origin: "大气中由氧分子在紫外线作用下形成，也可通过电晕放电或紫外线灯人工制备",
        funFacts: [
            "臭氧层位于距地面15-35公里的平流层",
            "臭氧的气味类似于氯气或电火花味",
            "臭氧比氧气重1.5倍",
            "液臭氧呈深蓝色",
            "臭氧是最强的氧化剂之一"
        ],
        history: "1839年舍恩拜因在电解稀硫酸时发现了臭氧，并注意到其特殊气味。1840年他正式发表了这一发现。20世纪初，人们发现臭氧能吸收紫外线，保护地球生命。1985年发现南极臭氧空洞，推动了国际环保合作。",
        description: "淡蓝色气体，有特殊气味，强氧化剂，臭氧层保护地球免受紫外线伤害"
    },
    {
        symbol: "NO₂",
        englishName: "Nitrogen Dioxide",
        chineseName: "二氧化氮",
        type: "化合物",
        formula: "NO₂",
        molecularWeight: 46.006,
        category: "无机化合物",
        phase: "气体",
        color: "红棕色",
        odor: "刺激性",
        acidBase: "酸性氧化物",
        discovery: "1772年由英国化学家约瑟夫·普利斯特里发现",
        origin: "由一氧化氮与氧气反应产生，主要来自汽车尾气和工业排放",
        funFacts: [
            "是光化学烟雾的主要成分之一",
            "低温时会聚合成四氧化二氮",
            "是酸雨形成的重要原因",
            "在火箭推进剂中用作氧化剂",
            "吸入会导致呼吸道疾病"
        ],
        history: "1772年普利斯特里通过硝酸与铜反应首次制得二氧化氮。19世纪工业革命期间，随着内燃机的发明和大量使用，二氧化氮成为主要空气污染物。20世纪50年代洛杉矶光化学烟雾事件后，人们开始重视其对环境和健康的影响。",
        description: "红棕色有毒气体，有刺激性气味，是主要空气污染物和酸雨前体物"
    },
    {
        symbol: "SO₂",
        englishName: "Sulfur Dioxide",
        chineseName: "二氧化硫",
        type: "化合物",
        formula: "SO₂",
        molecularWeight: 64.066,
        category: "无机化合物",
        phase: "气体",
        color: "无色",
        odor: "刺激性",
        acidBase: "酸性氧化物",
        discovery: "古代已知，18世纪拉瓦锡确定了其组成",
        origin: "火山喷发、化石燃料燃烧和工业过程产生",
        funFacts: [
            "是酸雨的主要成分之一",
            "可用于食品防腐和漂白",
            "古代用于漂白纺织品",
            "是葡萄酒酿造过程中的副产物"
        ],
        history: "二氧化硫在古代就被用于漂白纺织品和纸张。18世纪拉瓦锡通过实验确定了其化学组成。19世纪工业革命期间，随着煤炭的广泛使用，二氧化硫成为主要的空气污染物。20世纪人们开始认识到其对环境和健康的影响，推动了环保法规的制定。",
        description: "有刺激性气味的气体，形成酸雨"
    },
    {
        symbol: "HCl",
        englishName: "Hydrochloric Acid",
        chineseName: "盐酸",
        type: "化合物",
        formula: "HCl",
        molecularWeight: 36.461,
        category: "无机酸",
        phase: "液体",
        color: "无色",
        odor: "刺激性",
        acidBase: "强酸性",
        discovery: "约800年波斯炼金术士贾比尔发现，19世纪戴维确定组成",
        origin: "通过氢气和氯气直接合成，或从食盐电解副产物获得",
        funFacts: [
            "胃酸中盐酸的浓度约为0.1-0.5%",
            "浓盐酸会发出白烟（氯化氢气体）",
            "是古代'王水'的组成部分之一",
            "工业上用于金属清洗和食品加工"
        ],
        history: "古代被称为'盐精'，800年左右波斯炼金术士贾比尔首次制得。1808年戴维证明其为氢和氯的化合物，19世纪实现工业化生产。",
        description: "无色液体，有刺激性气味，胃酸的主要成分，用于金属清洗和食品加工"
    },
    {
        symbol: "NaOH",
        englishName: "Sodium Hydroxide",
        chineseName: "氢氧化钠",
        type: "化合物",
        formula: "NaOH",
        molecularWeight: 39.997,
        category: "无机碱",
        phase: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "强碱性",
        discovery: "1807年由英国化学家戴维通过电解法发现",
        origin: "通过电解食盐水制备，或从天然碱矿提取",
        funFacts: [
            "俗称'烧碱'或'苛性钠'",
            "易潮解，暴露在空气中会吸收水分和二氧化碳",
            "与油脂反应生成肥皂",
            "是制造纸张的重要化学品"
        ],
        history: "1807年戴维通过电解熔融的氢氧化钠首次分离出金属钠。19世纪末随着电解技术的进步，氢氧化钠开始大规模生产。",
        description: "白色固体，易潮解，强腐蚀性，用于制造肥皂、纸张和清洁剂"
    },
    {
        symbol: "Ca(OH)₂",
        englishName: "Calcium Hydroxide",
        chineseName: "氢氧化钙",
        type: "化合物",
        formula: "Ca(OH)₂",
        molecularWeight: 74.093,
        category: "无机碱",
        phase: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "碱性",
        discovery: "古代已知，18世纪化学家确定组成",
        origin: "通过生石灰（CaO）与水反应制备",
        funFacts: [
            "古代称为'熟石灰'",
            "用于制作传统灰浆和三合土",
            "是石灰水的溶质，用于检验二氧化碳",
            "在食品工业中用作添加剂E526"
        ],
        history: "古代人类就使用石灰作为建筑材料。通过煅烧石灰石得到生石灰，再加水制成。19世纪化学家确定了其化学组成。",
        description: "白色粉末，微溶于水，用于建筑、农业和食品工业"
    },
    {
        symbol: "CH₃COOH",
        englishName: "Acetic Acid",
        chineseName: "乙酸",
        type: "化合物",
        formula: "CH₃COOH",
        molecularWeight: 60.052,
        category: "有机酸",
        phase: "液体",
        color: "无色",
        odor: "刺激性醋味",
        acidBase: "弱酸性",
        discovery: "古代已知，18世纪拉瓦锡确定组成",
        origin: "通过发酵法或化学合成制备，天然存在于醋中",
        funFacts: [
            "食醋中乙酸含量通常为4-8%",
            "浓乙酸在低温下会凝固成冰状晶体",
            "是人类最早使用的有机酸之一",
            "在食品工业中用作添加剂E260"
        ],
        history: "古代人类通过发酵水果和谷物制得醋。1784年拉瓦锡证明醋的主要成分是乙酸。19世纪开始工业化生产。",
        description: "无色液体，有刺激性醋味，弱酸性，是食醋的主要成分"
    },
    {
        symbol: "C₁₂H₂₂O₁₁",
        englishName: "Sucrose",
        chineseName: "蔗糖",
        type: "化合物",
        formula: "C₁₂H₂₂O₁₁",
        molecularWeight: 342.297,
        category: "有机化合物",
        phase: "固体",
        color: "白色",
        odor: "无味",
        acidBase: "中性",
        discovery: "古代已知，19世纪化学家确定结构",
        origin: "主要从甘蔗和甜菜中提取，通过结晶精制得到",
        funFacts: [
            "是地球上最丰富的有机化合物之一",
            "在酸性条件下会水解成葡萄糖和果糖",
            "加热到186°C会焦糖化产生焦糖",
            "一个蔗糖分子由12个碳原子、22个氢原子和11个氧原子组成"
        ],
        history: "古代印度和中国就使用甘蔗制糖。18世纪欧洲开始大规模种植甜菜制糖。19世纪化学家确定了蔗糖的化学结构。",
        description: "白色晶体，有甜味，易溶于水，是常见的食糖和能量来源"
    },
    {
        symbol: "CO",
        englishName: "Carbon Monoxide",
        chineseName: "一氧化碳",
        type: "化合物",
        formula: "CO",
        molecularWeight: 28.010,
        category: "无机化合物",
        phase: "气体",
        color: "无色",
        odor: "无味",
        acidBase: "中性氧化物",
        discovery: "1776年由法国化学家拉索内发现",
        origin: "不完全燃烧产生，火山喷发和森林火灾也会自然产生",
        funFacts: [
            "被称为'无声杀手'，因为它无色无味",
            "与血红蛋白结合能力是氧气的200倍",
            "汽车尾气是主要的人为来源",
            "古代用于执行死刑的毒气"
        ],
        history: "1776年法国化学家拉索内通过加热木炭和氧化锌首次制得。19世纪工业革命期间，随着煤炭的广泛使用，人们开始认识到其毒性。",
        description: "无色无味的有毒气体，与血红蛋白结合导致缺氧"
    },
    {
        symbol: "H₂O₂",
        englishName: "Hydrogen Peroxide",
        chineseName: "过氧化氢",
        type: "化合物",
        formula: "H₂O₂",
        molecularWeight: 34.015,
        category: "无机化合物",
        phase: "液体",
        color: "无色",
        odor: "微弱刺激性",
        acidBase: "弱酸性",
        discovery: "1818年由法国化学家泰纳尔发现",
        origin: "通过蒽醌法工业制备，也可通过电解法制得",
        funFacts: [
            "3%溶液称为'双氧水'，是家用消毒剂",
            "高浓度时可用于火箭推进剂",
            "在生物体内会自然产生和分解",
            "分解产生氧气和水，环保无污染"
        ],
        history: "1818年泰纳尔通过氧化钡和硝酸反应首次制得。19世纪后期开始工业化生产，第一次世界大战期间用于漂白纺织品。",
        description: "无色液体，易分解产生氧气，3%溶液用作消毒剂，高浓度为强氧化剂"
    },
    {
        symbol: "N₂O",
        englishName: "Nitrous Oxide",
        chineseName: "一氧化二氮",
        type: "化合物",
        formula: "N₂O",
        molecularWeight: 44.013,
        category: "无机化合物",
        phase: "气体",
        color: "无色",
        odor: "微甜气味",
        acidBase: "中性",
        discovery: "1772年由英国化学家普利斯特里发现",
        origin: "通过硝酸铵热分解制备，也存在于大气中微量",
        funFacts: [
            "吸入后会使人发笑，因此得名'笑气'",
            "曾用于19世纪的'笑气派对'",
            "现代用作火箭推进剂的氧化剂",
            "在牙科手术中用作麻醉剂"
        ],
        history: "1772年普利斯特里通过硝酸和铁反应首次制得。19世纪40年代被用作麻醉剂，是世界上第一个被使用的麻醉气体。",
        description: "无色气体，有甜味，吸入后产生欣快感，用作麻醉剂和火箭推进剂"
    },
    {
        symbol: "SiO₂",
        englishName: "Silicon Dioxide",
        chineseName: "二氧化硅",
        type: "化合物",
        formula: "SiO₂",
        molecularWeight: 60.085,
        category: "无机化合物",
        phase: "固体",
        color: "无色或白色",
        odor: "无味",
        acidBase: "酸性氧化物",
        discovery: "古代已知，19世纪化学家确定组成",
        origin: "天然存在于石英、沙子、石英石中，也可人工合成",
        funFacts: [
            "是地壳中含量第二多的化合物",
            "石英晶体具有压电效应",
            "玻璃的主要成分",
            "硅藻土是硅藻的二氧化硅遗骸"
        ],
        history: "古代人类就使用石英制作工具和装饰品。19世纪化学家确定了其化学组成，20世纪开始大规模用于电子工业。",
        description: "无色固体，硬度高，不溶于水，是石英、沙子的主要成分"
    },
    {
        symbol: "Al₂O₃",
        englishName: "Aluminum Oxide",
        chineseName: "氧化铝",
        type: "化合物",
        formula: "Al₂O₃",
        molecularWeight: 101.961,
        category: "无机化合物",
        description: "刚玉、红宝石、蓝宝石的主要成分"
    },
    {
        symbol: "Fe₂O₃",
        englishName: "Iron(III) Oxide",
        chineseName: "氧化铁",
        type: "化合物",
        formula: "Fe₂O₃",
        molecularWeight: 159.687,
        category: "无机化合物",
        description: "铁锈的主要成分，红色颜料"
    },
    {
        symbol: "CuSO₄",
        englishName: "Copper(II) Sulfate",
        chineseName: "硫酸铜",
        type: "化合物",
        formula: "CuSO₄",
        molecularWeight: 159.609,
        category: "无机盐",
        description: "蓝色晶体，用于电镀和杀菌剂"
    },
    {
        symbol: "AgNO₃",
        englishName: "Silver Nitrate",
        chineseName: "硝酸银",
        type: "化合物",
        formula: "AgNO₃",
        molecularWeight: 169.873,
        category: "无机盐",
        description: "用于制造镜子和检验卤素离子"
    },
    {
        symbol: "KMnO₄",
        englishName: "Potassium Permanganate",
        chineseName: "高锰酸钾",
        type: "化合物",
        formula: "KMnO₄",
        molecularWeight: 158.034,
        category: "无机盐",
        description: "紫黑色晶体，强氧化剂，用于消毒"
    },
    {
        symbol: "C₆H₆",
        englishName: "Benzene",
        chineseName: "苯",
        type: "化合物",
        formula: "C₆H₆",
        molecularWeight: 78.114,
        category: "有机化合物",
        phase: "液体",
        color: "无色",
        odor: "特殊芳香味",
        acidBase: "中性",
        discovery: "1825年由英国化学家迈克尔·法拉第发现",
        origin: "从煤焦油中提炼得到，也可通过石油重整制得",
        funFacts: [
            "苯分子呈平面六边形结构，具有芳香性",
            "是芳香族化合物的母体",
            "曾用作溶剂和汽油添加剂，因致癌性已限制使用",
            "苯环结构由德国化学家凯库勒在1865年提出",
            "工业上主要用于制造塑料、合成纤维和橡胶"
        ],
        history: "1825年法拉第从压缩的照明气中首次分离出苯。1833年德国化学家米切里希确定了苯的组成。1865年德国化学家奥古斯特·凯库勒提出了苯的环状结构，这是有机化学史上的重要里程碑。19世纪后期开始工业化生产，20世纪成为重要的化工原料，但由于其致癌性，现代使用已受到严格限制。",
        description: "无色液体，有特殊芳香味，最简单的芳香烃，具有致癌性"
    },
    {
        symbol: "CH₃OH",
        englishName: "Methanol",
        chineseName: "甲醇",
        type: "化合物",
        formula: "CH₃OH",
        molecularWeight: 32.042,
        category: "有机化合物",
        description: "工业酒精，有毒"
    },
    {
        symbol: "C₂H₄",
        englishName: "Ethylene",
        chineseName: "乙烯",
        type: "化合物",
        formula: "C₂H₄",
        molecularWeight: 28.054,
        category: "有机化合物",
        description: "植物激素，用于催熟水果"
    },
    {
        symbol: "C₃H₈",
        englishName: "Propane",
        chineseName: "丙烷",
        type: "化合物",
        formula: "C₃H₈",
        molecularWeight: 44.096,
        category: "有机化合物",
        description: "液化石油气的主要成分"
    },
    {
        symbol: "C₄H₁₀",
        englishName: "Butane",
        chineseName: "丁烷",
        type: "化合物",
        formula: "C₄H₁₀",
        molecularWeight: 58.123,
        category: "有机化合物",
        description: "打火机燃料"
    },
    {
        symbol: "C₈H₁₈",
        englishName: "Octane",
        chineseName: "辛烷",
        type: "化合物",
        formula: "C₈H₁₈",
        molecularWeight: 114.231,
        category: "有机化合物",
        description: "汽油的主要成分之一"
    },
    {
        symbol: "C₂H₄O₂",
        englishName: "Acetic Acid",
        chineseName: "乙酸",
        type: "化合物",
        formula: "CH₃COOH",
        molecularWeight: 60.052,
        category: "有机酸",
        description: "食醋的主要成分"
    },
    {
        symbol: "NH₄Cl",
        englishName: "Ammonium Chloride",
        chineseName: "氯化铵",
        type: "化合物",
        formula: "NH₄Cl",
        molecularWeight: 53.491,
        category: "无机盐",
        description: "用于干电池和肥料"
    },
    {
        symbol: "CuO",
        englishName: "Copper(II) Oxide",
        chineseName: "氧化铜",
        type: "化合物",
        formula: "CuO",
        molecularWeight: 79.545,
        category: "无机化合物",
        description: "黑色粉末，用作催化剂"
    },
    {
        symbol: "ZnO",
        englishName: "Zinc Oxide",
        chineseName: "氧化锌",
        type: "化合物",
        formula: "ZnO",
        molecularWeight: 81.379,
        category: "无机化合物",
        description: "白色粉末，用于防晒霜和橡胶工业"
    },
    {
        symbol: "TiO₂",
        englishName: "Titanium Dioxide",
        chineseName: "二氧化钛",
        type: "化合物",
        formula: "TiO₂",
        molecularWeight: 79.866,
        category: "无机化合物",
        description: "白色颜料，用于涂料和防晒霜"
    },
    {
        symbol: "BaSO₄",
        englishName: "Barium Sulfate",
        chineseName: "硫酸钡",
        type: "化合物",
        formula: "BaSO₄",
        molecularWeight: 233.391,
        category: "无机盐",
        description: "白色粉末，医学上用作造影剂"
    },
    {
        symbol: "CaO",
        englishName: "Calcium Oxide",
        chineseName: "氧化钙",
        type: "化合物",
        formula: "CaO",
        molecularWeight: 56.077,
        category: "无机化合物",
        description: "生石灰，用于建筑和中和酸性土壤"
    },
    {
        symbol: "Na₂CO₃",
        englishName: "Sodium Carbonate",
        chineseName: "碳酸钠",
        type: "化合物",
        formula: "Na₂CO₃",
        molecularWeight: 105.989,
        category: "无机盐",
        description: "纯碱，用于制造洗涤剂和玻璃"
    },
    {
        symbol: "NaHCO₃",
        englishName: "Sodium Bicarbonate",
        chineseName: "碳酸氢钠",
        type: "化合物",
        formula: "NaHCO₃",
        molecularWeight: 84.007,
        category: "无机盐",
        description: "小苏打，用于烘焙和清洁"
    },
    {
        symbol: "K₂Cr₂O₇",
        englishName: "Potassium Dichromate",
        chineseName: "重铬酸钾",
        type: "化合物",
        formula: "K₂Cr₂O₇",
        molecularWeight: 294.185,
        category: "无机盐",
        description: "橙红色晶体，强氧化剂"
    },
    {
        symbol: "CoCl₂",
        englishName: "Cobalt(II) Chloride",
        chineseName: "氯化钴",
        type: "化合物",
        formula: "CoCl₂",
        molecularWeight: 129.839,
        category: "无机盐",
        description: "蓝色晶体，用作干燥剂指示剂"
    },
    {
        symbol: "NiSO₄",
        englishName: "Nickel(II) Sulfate",
        chineseName: "硫酸镍",
        type: "化合物",
        formula: "NiSO₄",
        molecularWeight: 154.757,
        category: "无机盐",
        description: "绿色晶体，用于电镀"
    },
    {
        symbol: "MnO₂",
        englishName: "Manganese Dioxide",
        chineseName: "二氧化锰",
        type: "化合物",
        formula: "MnO₂",
        molecularWeight: 86.937,
        category: "无机化合物",
        description: "黑色粉末，用作催化剂"
    },
    {
        symbol: "PbS",
        englishName: "Lead(II) Sulfide",
        chineseName: "硫化铅",
        type: "化合物",
        formula: "PbS",
        molecularWeight: 239.265,
        category: "无机化合物",
        description: "黑色晶体，方铅矿的主要成分"
    },
    {
        symbol: "FeS₂",
        englishName: "Iron Pyrite",
        chineseName: "二硫化铁",
        type: "化合物",
        formula: "FeS₂",
        molecularWeight: 119.979,
        category: "无机化合物",
        description: "黄铁矿，俗称愚人金"
    },
    {
        symbol: "Cu₂O",
        englishName: "Copper(I) Oxide",
        chineseName: "氧化亚铜",
        type: "化合物",
        formula: "Cu₂O",
        molecularWeight: 143.091,
        category: "无机化合物",
        description: "红色粉末，用作颜料"
    },
    {
        symbol: "HgCl₂",
        englishName: "Mercury(II) Chloride",
        chineseName: "氯化汞",
        type: "化合物",
        formula: "HgCl₂",
        molecularWeight: 271.495,
        category: "无机盐",
        description: "白色晶体，剧毒，用作消毒剂"
    },
    {
        symbol: "As₂O₃",
        englishName: "Arsenic Trioxide",
        chineseName: "三氧化二砷",
        type: "化合物",
        formula: "As₂O₃",
        molecularWeight: 197.841,
        category: "无机化合物",
        description: "白色粉末，剧毒，俗称砒霜"
    },
    {
        symbol: "C₂₀H₄₂",
        englishName: "Eicosane",
        chineseName: "二十烷",
        type: "化合物",
        formula: "C₂₀H₄₂",
        molecularWeight: 282.547,
        category: "有机化合物",
        description: "固体烷烃，石蜡的主要成分"
    },
    {
        symbol: "C₆H₅OH",
        englishName: "Phenol",
        chineseName: "苯酚",
        type: "化合物",
        formula: "C₆H₅OH",
        molecularWeight: 94.111,
        category: "有机化合物",
        description: "石碳酸，用作消毒剂和化工原料"
    },
    {
        symbol: "HCHO",
        englishName: "Formaldehyde",
        chineseName: "甲醛",
        type: "化合物",
        formula: "HCHO",
        molecularWeight: 30.026,
        category: "有机化合物",
        description: "有刺激性气味的气体，用于防腐"
    },
    {
        symbol: "CCl₄",
        englishName: "Carbon Tetrachloride",
        chineseName: "四氯化碳",
        type: "化合物",
        formula: "CCl₄",
        molecularWeight: 153.823,
        category: "有机化合物",
        phase: "液体",
        color: "无色",
        odor: "特殊气味",
        acidBase: "中性",
        discovery: "1839年由法国化学家亨利·维克托·勒尼奥发现",
        origin: "通过甲烷氯化或二硫化碳氯化制备",
        funFacts: [
            "曾用作灭火器和干洗溶剂",
            "是臭氧层破坏物质之一",
            "在紫外灯下会分解产生有毒的光气",
            "20世纪中期是最常用的有机溶剂之一"
        ],
        history: "1839年法国化学家勒尼奥通过甲烷氯化首次制得四氯化碳。19世纪后期开始工业化生产。20世纪中期广泛用于干洗、灭火器和脱脂剂。1970年代发现其对臭氧层的破坏作用，逐步被禁用。",
        description: "无色液体，优良的有机溶剂"
    },
    {
        symbol: "CHCl₃",
        englishName: "Chloroform",
        chineseName: "氯仿",
        type: "化合物",
        formula: "CHCl₃",
        molecularWeight: 119.378,
        category: "有机化合物",
        description: "无色液体，曾用作麻醉剂"
    },
    {
        symbol: "C₆H₄(CH₃)₂",
        englishName: "Xylene",
        chineseName: "二甲苯",
        type: "化合物",
        formula: "C₈H₁₀",
        molecularWeight: 106.165,
        category: "有机化合物",
        description: "无色液体，用作溶剂"
    },
    {
        symbol: "C₁₀H₈",
        englishName: "Naphthalene",
        chineseName: "萘",
        type: "化合物",
        formula: "C₁₀H₈",
        molecularWeight: 128.171,
        category: "有机化合物",
        phase: "固体",
        color: "白色",
        odor: "特殊气味",
        acidBase: "中性",
        discovery: "1820年由英国化学家发现",
        origin: "从煤焦油中提炼得到，也存在于石油中",
        funFacts: [
            "从煤焦油中提取的第一个芳香化合物",
            "分子呈平面结构，两个苯环共用两个碳原子",
            "天然存在于烟草和某些植物中",
            "印度传统使用萘球防虫有数百年历史"
        ],
        history: "萘最早从煤焦油中分离得到，是人类从煤焦油中提取的第一个芳香化合物。19世纪中期开始工业化生产，最初用于染料工业，后来广泛用于防虫剂。",
        description: "白色固体，有特殊气味，易升华，防虫丸的主要成分"
    },
    {
        symbol: "C₁₄H₁₀",
        englishName: "Anthracene",
        chineseName: "蒽",
        type: "化合物",
        formula: "C₁₄H₁₀",
        molecularWeight: 178.229,
        category: "有机化合物",
        description: "白色晶体，用于制造染料"
    },
    {
        symbol: "C₆H₅NH₂",
        englishName: "Aniline",
        chineseName: "苯胺",
        type: "化合物",
        formula: "C₆H₇N",
        molecularWeight: 93.126,
        category: "有机化合物",
        description: "无色液体，用于制造染料和药物"
    },
    {
        symbol: "C₆H₅NO₂",
        englishName: "Nitrobenzene",
        chineseName: "硝基苯",
        type: "化合物",
        formula: "C₆H₅NO₂",
        molecularWeight: 123.109,
        category: "有机化合物",
        description: "淡黄色液体，有苦杏仁味"
    },
    {
        symbol: "C₇H₈",
        englishName: "Toluene",
        chineseName: "甲苯",
        type: "化合物",
        formula: "C₇H₈",
        molecularWeight: 92.139,
        category: "有机化合物",
        phase: "液体",
        color: "无色",
        odor: "特殊芳香味",
        acidBase: "中性",
        discovery: "1837年由法国化学家奥古斯特·罗朗发现",
        origin: "从煤焦油中提炼得到，也可通过石油重整制得",
        funFacts: [
            "是TNT炸药的前体",
            "用作油漆稀释剂和工业溶剂",
            "是制造聚氨酯泡沫的原料",
            "吸入高浓度甲苯会导致中毒",
            "指甲油的成分之一"
        ],
        history: "1837年法国化学家罗朗从吐鲁香脂中发现了甲苯，并以其来源命名。19世纪后期开始工业化生产，最初用于染料工业。20世纪随着石化工业的发展，甲苯成为重要的化工原料，广泛用于溶剂、炸药和塑料工业。",
        description: "无色液体，有特殊芳香味，是重要溶剂和化工原料"
    },
    {
        symbol: "C₂H₄O",
        englishName: "Acetaldehyde",
        chineseName: "乙醛",
        type: "化合物",
        formula: "C₂H₄O",
        molecularWeight: 44.052,
        category: "有机化合物",
        description: "有刺激性气味的液体，易挥发"
    },
    {
        symbol: "C₃H₆O",
        englishName: "Acetone",
        chineseName: "丙酮",
        type: "化合物",
        formula: "C₃H₆O",
        molecularWeight: 58.079,
        category: "有机化合物",
        description: "无色液体，优良的有机溶剂"
    },
    {
        symbol: "C₂H₃N",
        englishName: "Acetonitrile",
        chineseName: "乙腈",
        type: "化合物",
        formula: "C₂H₃N",
        molecularWeight: 41.052,
        category: "有机化合物",
        description: "无色液体，用作溶剂"
    },
    {
        symbol: "CS₂",
        englishName: "Carbon Disulfide",
        chineseName: "二硫化碳",
        type: "化合物",
        formula: "CS₂",
        molecularWeight: 76.139,
        category: "有机化合物",
        description: "无色液体，极易挥发和燃烧"
    },
    {
        symbol: "B₂H₆",
        englishName: "Diborane",
        chineseName: "乙硼烷",
        type: "化合物",
        formula: "B₂H₆",
        molecularWeight: 27.670,
        category: "无机化合物",
        description: "无色气体，硼氢化合物"
    },
    {
        symbol: "SiH₄",
        englishName: "Silane",
        chineseName: "硅烷",
        type: "化合物",
        formula: "SiH₄",
        molecularWeight: 32.118,
        category: "无机化合物",
        description: "无色气体，硅的氢化物"
    },
    {
        symbol: "PH₃",
        englishName: "Phosphine",
        chineseName: "磷化氢",
        type: "化合物",
        formula: "PH₃",
        molecularWeight: 33.998,
        category: "无机化合物",
        description: "有臭鱼味的气体，剧毒"
    },
    {
        symbol: "H₂S",
        englishName: "Hydrogen Sulfide",
        chineseName: "硫化氢",
        type: "化合物",
        formula: "H₂S",
        molecularWeight: 34.081,
        category: "无机化合物",
        description: "有臭鸡蛋味的气体，剧毒"
    },
    {
        symbol: "OF₂",
        englishName: "Oxygen Difluoride",
        chineseName: "二氟化氧",
        type: "化合物",
        formula: "OF₂",
        molecularWeight: 53.996,
        category: "无机化合物",
        description: "无色气体，强氧化剂"
    },
    {
        symbol: "ClO₂",
        englishName: "Chlorine Dioxide",
        chineseName: "二氧化氯",
        type: "化合物",
        formula: "ClO₂",
        molecularWeight: 67.452,
        category: "无机化合物",
        description: "黄绿色气体，强氧化剂"
    },
    {
        symbol: "XeF₆",
        englishName: "Xenon Hexafluoride",
        chineseName: "六氟化氙",
        type: "化合物",
        formula: "XeF₆",
        molecularWeight: 245.283,
        category: "无机化合物",
        description: "无色晶体，稀有气体化合物"
    },
    {
        symbol: "KrF₂",
        englishName: "Krypton Difluoride",
        chineseName: "二氟化氪",
        type: "化合物",
        formula: "KrF₂",
        molecularWeight: 121.795,
        category: "无机化合物",
        description: "无色晶体，稀有气体化合物"
    },
    {
        symbol: "SF₆",
        englishName: "Sulfur Hexafluoride",
        chineseName: "六氟化硫",
        type: "化合物",
        formula: "SF₆",
        molecularWeight: 146.056,
        category: "无机化合物",
        description: "无色气体，优良的绝缘体"
    },
    {
        symbol: "PCl₅",
        englishName: "Phosphorus Pentachloride",
        chineseName: "五氯化磷",
        type: "化合物",
        formula: "PCl₅",
        molecularWeight: 208.239,
        category: "无机化合物",
        description: "白色固体，用作氯化剂"
    },
    {
        symbol: "V₂O₅",
        englishName: "Vanadium(V) Oxide",
        chineseName: "五氧化二钒",
        type: "化合物",
        formula: "V₂O₅",
        molecularWeight: 181.880,
        category: "无机化合物",
        description: "橙黄色粉末，用作催化剂"
    },
    {
        symbol: "Cr₂O₃",
        englishName: "Chromium(III) Oxide",
        chineseName: "三氧化二铬",
        type: "化合物",
        formula: "Cr₂O₃",
        molecularWeight: 151.990,
        category: "无机化合物",
        description: "绿色粉末，用作绿色颜料"
    },
    {
        symbol: "MoS₂",
        englishName: "Molybdenum Disulfide",
        chineseName: "二硫化钼",
        type: "化合物",
        formula: "MoS₂",
        molecularWeight: 160.073,
        category: "无机化合物",
        description: "黑色固体，用作固体润滑剂"
    },
    {
        symbol: "WS₂",
        englishName: "Tungsten Disulfide",
        chineseName: "二硫化钨",
        type: "化合物",
        formula: "WS₂",
        molecularWeight: 247.979,
        category: "无机化合物",
        description: "黑色固体，用作固体润滑剂"
    },
    {
        symbol: "CdS",
        englishName: "Cadmium Sulfide",
        chineseName: "硫化镉",
        type: "化合物",
        formula: "CdS",
        molecularWeight: 144.477,
        category: "无机化合物",
        description: "黄色固体，用作黄色颜料"
    },
    {
        symbol: "HgS",
        englishName: "Mercury(II) Sulfide",
        chineseName: "硫化汞",
        type: "化合物",
        formula: "HgS",
        molecularWeight: 232.655,
        category: "无机化合物",
        description: "红色固体，朱砂的主要成分"
    },
    {
        symbol: "SnO₂",
        englishName: "Tin(IV) Oxide",
        chineseName: "二氧化锡",
        type: "化合物",
        formula: "SnO₂",
        molecularWeight: 150.709,
        category: "无机化合物",
        description: "白色固体，用于制造透明导电膜"
    },
    {
        symbol: "Bi₂O₃",
        englishName: "Bismuth(III) Oxide",
        chineseName: "三氧化二铋",
        type: "化合物",
        formula: "Bi₂O₃",
        molecularWeight: 465.959,
        category: "无机化合物",
        description: "黄色固体，用作颜料和催化剂"
    },
    {
        symbol: "Sb₂S₃",
        englishName: "Antimony(III) Sulfide",
        chineseName: "三硫化二锑",
        type: "化合物",
        formula: "Sb₂S₃",
        molecularWeight: 339.718,
        category: "无机化合物",
        description: "黑色固体，用于制造火柴"
    },
    {
        symbol: "As₂S₃",
        englishName: "Arsenic(III) Sulfide",
        chineseName: "三硫化二砷",
        type: "化合物",
        formula: "As₂S₃",
        molecularWeight: 246.038,
        category: "无机化合物",
        description: "黄色固体，用作颜料"
    },
    {
        symbol: "LiOH",
        englishName: "Lithium Hydroxide",
        chineseName: "氢氧化锂",
        type: "化合物",
        formula: "LiOH",
        molecularWeight: 23.948,
        category: "无机碱",
        description: "白色固体，用于制造锂电池"
    },
    {
        symbol: "RbOH",
        englishName: "Rubidium Hydroxide",
        chineseName: "氢氧化铷",
        type: "化合物",
        formula: "RbOH",
        molecularWeight: 102.475,
        category: "无机碱",
        description: "白色固体，强碱性"
    },
    {
        symbol: "CsOH",
        englishName: "Cesium Hydroxide",
        chineseName: "氢氧化铯",
        type: "化合物",
        formula: "CsOH",
        molecularWeight: 149.913,
        category: "无机碱",
        description: "白色固体，最强的碱之一"
    },
    {
        symbol: "BeO",
        englishName: "Beryllium Oxide",
        chineseName: "氧化铍",
        type: "化合物",
        formula: "BeO",
        molecularWeight: 25.011,
        category: "无机化合物",
        description: "白色固体，优良的导热体"
    },
    {
        symbol: "MgO",
        englishName: "Magnesium Oxide",
        chineseName: "氧化镁",
        type: "化合物",
        formula: "MgO",
        molecularWeight: 40.304,
        category: "无机化合物",
        description: "白色固体，耐火材料"
    },
    {
        symbol: "SrO",
        englishName: "Strontium Oxide",
        chineseName: "氧化锶",
        type: "化合物",
        formula: "SrO",
        molecularWeight: 103.619,
        category: "无机化合物",
        description: "白色固体，用于制造红色焰火"
    },
    {
        symbol: "BaO",
        englishName: "Barium Oxide",
        chineseName: "氧化钡",
        type: "化合物",
        formula: "BaO",
        molecularWeight: 153.326,
        category: "无机化合物",
        description: "白色固体，用于制造绿色焰火"
    },
    {
        symbol: "K₂O",
        englishName: "Potassium Oxide",
        chineseName: "氧化钾",
        type: "化合物",
        formula: "K₂O",
        molecularWeight: 94.196,
        category: "无机化合物",
        description: "白色固体，强碱性"
    },
    {
        symbol: "Na₂O",
        englishName: "Sodium Oxide",
        chineseName: "氧化钠",
        type: "化合物",
        formula: "Na₂O",
        molecularWeight: 61.979,
        category: "无机化合物",
        description: "白色固体，强碱性"
    },
    {
        symbol: "Li₂O",
        englishName: "Lithium Oxide",
        chineseName: "氧化锂",
        type: "化合物",
        formula: "Li₂O",
        molecularWeight: 29.881,
        category: "无机化合物",
        description: "白色固体，用于制造玻璃"
    }
];

// 导出数据供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = chemicalData;
}